version: '3.7'

services:

  interactive-test:
    container_name: interactive-test
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8443:3000
    environment:
      - CHOKIDAR_USEPOLLING=true   
    stdin_open: true 